import json
import os
from django import template
from django.conf import settings

register = template.Library()


@register.simple_tag
def vite_asset(asset_key: str, asset_type: str = "js") -> str:
    """
    Returns the asset file path from the manifest.json.

    :param asset_key: The key in manifest.json (e.g., "index.html").
    :param asset_type: Type of asset to return: "js" (default) or "css".
    :return: The filename for the asset, or an empty string if not found.
    """
    manifest_path = os.path.join(settings.BASE_DIR, 'static', 'frontend', '.vite', 'manifest.json')
    
    try:
        with open(manifest_path, 'r') as f:
            manifest = json.load(f)
    except FileNotFoundError:
        return ''

    asset_info = manifest.get(asset_key)
    if not asset_info:
        return ''

    if asset_type == "js":
        # Return the JS file generated by Vite.
        return asset_info.get("file", "")
    elif asset_type == "css":
        # Return the first CSS file from the "css" list.
        css_files = asset_info.get("css", [])
        return css_files[0] if css_files else ''
    else:
        return ''
